### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [2]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [4]:
### code here
a=np.zeros((10,))
b=np.ones((10,),)
c=np.full((10,),5,dtype=float)
print('An array of 10 zeros:')
print(a)
print('An array of 10 ones:')
print(b)
print('An array of 10 fives:')
print(c)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
## sample output

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [5]:
### code here
a=np.arange(30,71)
print("Array of the integers from 30 to70")
print(a)

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
### sample output

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [ ]:
### code here
x=np.arange(10,50)
a=x[(x%2==0)]
print('Array of all the even integers from 10 to 50')
print(a)

In [ ]:
## sample output


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [6]:
### code here
a=np.eye(3)
print("3x3 matrix:")
print(a)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## sample output

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [7]:
### code here
import random as rd
a=np.random.random((1,))
print("Random number between 0 and 1:")
print(a)

Random number between 0 and 1:
[0.27962812]


In [ ]:
## sample output

Random number between 0 and 1:
[0.40400053]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [5]:
## code here
a=np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(a)

15 random numbers from a standard normal distribution:
[-1.58891986 -0.02528839 -1.37394528 -1.5229197  -0.60671589  1.21044453
 -1.4096462   0.2843373   0.27101784  0.35734893 -0.48517465  1.12783275
 -0.04718158 -0.62603972  2.02893302]


In [ ]:
## sample output

15 random numbers from a standard normal distribution:
[ 0.68439314  1.50916987 -0.75364839  0.1038106   0.07789927 -0.15349755
  1.78151615  0.49989426  0.18791322 -1.51931266 -0.55512066  2.02808972
  0.37648568  0.57999878 -0.31095957]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [6]:
## code here
a=np.arange(10,22)
arr=np.arange(10,22).reshape(3,4)
print("Original array:")
print(arr)
print('Each element of the array is:')
print(a)

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
[10 11 12 13 14 15 16 17 18 19 20 21]


In [ ]:
## sample output

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [4]:
## code herea=np.array([1, 8, 3, 5])
a=np.array([1, 8, 3, 5])
b=np.array([10,  1,  4, 10])
c=a*b
print("Vector-1")
print(a)
print("Vector-2")
print(b)
print("Multiply the values of two said vectors:")
print(c)

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


In [ ]:
## sample output

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [8]:
### code here
a=np.arange(12,38)
b=a[::-1]
print("Original array:")
print(a)
print("Reverse array:")
print(b)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [1]:
## sample output

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [7]:
## code here
a=np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
## sample output

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [3]:
## code here
a=np.arange(4,).reshape(2,2)
b=np.sum(a)
c=np.sum(a, axis=0)
d=np.sum(a, axis=1)
print("Original array:")
print(a)
print("Sum of all elements:")
print(b)
print("Sum of each row:")
print(c)
print("Sum of each row:")
print(d)

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each row:
[2 4]
Sum of each row:
[1 5]


In [ ]:
## sample output

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [3]:
## code here
a=np.array([4, 5])
b=np.array([7, 10])
c=np.dot(a,b)
print("Original vectors:")
print(a)
print(b)
print("Inner product of said vectors:")
print(c)

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


In [ ]:
## sample output

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
