### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [2]:
import numpy as np
### code here
a=np.array([[3, 2, np.nan, 1],
              [10, 12, 10, 9],
              [5, np.nan, 1, np.nan]])
b=np.isnan(a)
print("Original array:")
print(a)
print("Find the missing data of the said array:")
print(b)

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]
Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [ ]:
### code here 

###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [3]:
## code here
import numpy as np
a=np.arange(16, dtype='int').reshape(-1, 4)
b=a[::-1]
print("Original array:")
print(a)
print("New array after swapping first and last rows of the said array:")
print(b)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [4]:
#### code here
lis=[1, 2, 3, 4, 5, 6, 7, 8]
a=np.asarray(lis)
tupl=([8, 4, 6], [1, 2, 3])
b=np.asarray(tupl)
print("List array: ")
print(a)
print("Tuple array: ")
print(b)

List array: 
[1 2 3 4 5 6 7 8]
Tuple array: 
[[8 4 6]
 [1 2 3]]


###### 5. Write a NumPy program to find common values between two arrays.

In [ ]:
### code here

###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [6]:
### code here
a=np.arange(1,7).reshape(3,2)
b=a.reshape(2,3)
print("Reshape 3x2:")
print(a)
print("Reshape 2x3:")
print(b)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [8]:
### code here
x=np.array([10,10,20,10,20,20,20,30, 30,50,40,40])
a=np.unique(x)
print("Original array:")
print(x)
print("Frequency of unique values of the said array:")
print(a)

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[10 20 30 40 50]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [9]:
### code here
a=np.array([[0, 0, 0],
              [1, 2, 3],
              [4, 5, 6]]) 
b=np.array([10, 11, 12])
c=a+b
print("Original arrays:")
print(a)
print("Array-2")
print(b)
print("New Array:")
print(c)

Original arrays:
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]
New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [10]:
### code here
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [11]:
## code here
a=np.array([[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15]]) 
a
b=a[0:2,2:]
b
print("Original array:")
print(a)
print("\nExtracted data: Third and fourth elements of the first and second rows ")
print(b)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [ ]:
### code here

###### 12. Write a NumPy program to find the first Monday in May 2017.

In [ ]:
## code here

In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
